---
build:
  image: node:22
  stage: build
  script:
    - corepack enable
    - yarn install --immutable
    - yarn test
    - yarn lint
    - yarn build
  variables:
    YARN_CACHE_FOLDER: .yarn-cache/
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/

.deploy:
  image: alpine:latest
  stage: deploy
  dependencies:
    - build
  script:
    - apk add openssl openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -avz -e 'ssh -p2201' dist/ $SFTP_SERVER

build editor:
  extends: build
  variables:
    VITE_TEXTCAT_EDITOR: "1"

deploy to editor-dev:
  extends: .deploy
  dependencies:
    - build editor
  environment:
    name: editor-dev
  only:
    - master

deploy to editor-dev:manual:
  extends: .deploy
  dependencies:
    - build editor
  environment:
    name: editor-dev
  when: manual

deploy to editor:
  extends: .deploy
  dependencies:
    - build editor
  environment:
    name: editor
  when: manual

deploy to development:
  extends: .deploy
  dependencies:
    - build
  environment:
    name: development
  only:
    - master

deploy to development:manual:
  extends: .deploy
  dependencies:
    - build
  environment:
    name: development
  when: manual

deploy to production:
  extends: .deploy
  dependencies:
    - build
  environment:
    name: production
  only:
    - tags
  when: manual
