catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
minimumReleaseAgeExclude:
  - flatted@3.4.0
  - flatted@3.4.2
  - picomatch@2.3.2
  - picomatch@4.0.4
  - yaml@2.8.3
  - postcss@8.5.10
  - vite-plus@0.1.17
  - ws@8.20.1
  - brace-expansion@5.0.6
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
